// Original Link: https://cloudproxy.setpac.ge.com/pac.pac
// Changes
// 1. Replace all Proxy to Singapore node
// 2. Add ad-blocking domains to SendToOtherProxy2, and set Other_Proxy2 to 127.0.0.1:9
//--------------------------GE Standard PAC File------------------------------------------
// Owner: @CORP PAC Support
// Template - China
// Name - CSSpaSCNchina20, CSS=shared, pa=PAC, S=ASPAC, CH=China, 20
// Version - 1.0.c0.827
// LastChange - 27-Aug-2026
//----------------------------------------------------------------------------------------
// Define Proxies here
var Main_Proxy        = "PROXY PITC-Zscaler-ASPAC-Singapore3PR.proxy.corporate.ge.com:80";
var Other_Proxy       = "PROXY PITC-Zscaler-ASPAC-Singapore3PR.proxy.corporate.ge.com:80";
var Other_Proxy2      = "PROXY 127.0.0.1:9";
var pZen              = "PROXY PITC-Zscaler-ASPAC-Singapore3PR.proxy.corporate.ge.com:80";
var AD_Proxy          = "PROXY adproxy.o365.ge.com:443";
var EXOL_ExpressRoute = "PROXY exol.proxy.ge.com:80";
// End of ProxyList

// Variable to store IP Address Validation RegEx, Used in function FindProxyForURL
var ipv4addr = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;

// All PAC entries will go in HOSTS Array.
var HOSTS = [];

HOSTS = {
    // Only GE Internal Domains are supposed to go in SplitDNSDomains.
    SplitDNSDomains: [
        ".adf.azure.com",
        ".afs.azure.net",
        ".agentsvc.azure-automation.net",
        ".alstom.com",
        ".amazonaws.com",
        ".areva-td.com",
        ".azconfig.io",
        ".azure-automation.net",
        ".azure-devices.net",
        ".azurecr.io",
        ".azuresynapse.net",
        ".azurewebsites.net",
        ".batch.azure.com",
        ".bkmedical.com",
        ".blob.core.windows.net",
        ".cassandra.cosmos.azure.com",
        ".cytiva.com",
        ".database.windows.net",
        ".datafactory.azure.net",
        ".dev.azuresynapse.net",
        ".dfs.core.windows.net",
        ".digitaltwins.azure.net",
        ".documents.azure.com",
        ".elasticbeanstalk.com",
        ".esca.com",
        ".eventgrid.azure.net",
        ".file.core.windows.net",
        ".ge.com",
        ".geae.com",
        ".geblue.net",
        ".gremlin.cosmos.azure.com",
        ".gs-inc.com",
        ".lmwindpower.com",
        ".managedhsm.azure.net",
        ".mariadb.database.azure.com",
        ".media.azure.net",
        ".mongo.cosmos.azure.com",
        ".monitor.azure.com",
        ".mysql.database.azure.com",
        ".ods.opinsights.azure.com",
        ".oms.opinsights.azure.com",
        ".on.aws",
        ".prod.migration.windowsazure.com",
        ".purview.azure.com",
        ".purviewstudio.azure.com",
        ".redis.cache.windows.net",
        ".redisenterprise.cache.azure.net",
        ".search.windows.net",
        ".service.signalr.net",
        ".servicebus.windows.net",
        ".siterecovery.windowsazure.com",
        ".sql.azuresynapse.net",
        ".table.cosmos.azure.com",
        ".vault.azure.net",
        ".vaultcore.azure.net",
        ".vmwarevmc.com"
    ],
    //EndSplitDNSDomains

    // for external third parties which permits traffic only for GE specific subnets.
    SendToZen: [
        "*-one-self.gehealthcare.at",
        "*-one-self.gehealthcare.be",
        "*-one-self.gehealthcare.de",
        "*-one-self.gehealthcare.dk",
        "*-one-self.gehealthcare.es",
        "*-one-self.gehealthcare.fi",
        "*-one-self.gehealthcare.fr",
        "*-one-self.gehealthcare.it",
        "*-one-self.gehealthcare.no",
        "*-one-self.gehealthcare.se",
        "*-services.gehealthcare.ca",
        "*-services.gehealthcare.co.uk",
        "*-services.gehealthcare.com",
        "*-services.gehealthcare.com.au",
        "*-services.gehealthcare.com.br",
        "*-services.gehealthcare.in",
        "*-services.gehealthcare.jp",
        "*-services.gehealthcare.sa",
        ".15.energy",
        ".aa-rt.sharepoint.com",
        ".access-na1.mobileiron.com",
        ".anaqua.com",
        ".atp.azure.us",
        ".autodeskplm360.net",
        ".aws-usw02-pr.predix.io",
        ".azure.us",
        ".cytivalifesciences.io",
        ".dev.azure.com",
        ".dibbs.bsm.dla.mil",
        ".dn.theoffnet.com",
        ".fmsanywhere.com",
        ".ge-demo.com",
        ".gecis.io",
        ".gehealthcare.com",
        ".gev-demo.com",
        ".github.com",
        ".github.software.gevernova.com",
        ".githubdev.software.gevernova.com",
        ".gov.wiz.io",
        ".hambleaero.com",
        ".ice.predix.io",
        ".inl.gov",
        ".inpo.org",
        ".internalapmnow.com",
        ".jfrog.io",
        ".jsfvpc.lmtas.com",
        ".lavoro.gov.it",
        ".markit.com",
        ".markitserv.com",
        ".mckinseywave.com",
        ".mural-gehc.com",
        ".officeapps.live.com",
        ".officecdn.microsoft.com",
        ".predix.com",
        ".pushfp.svc.ms",
        ".security.us",
        ".service.windows.usgovcloud.microsoft",
        ".sharepoint.us",
        ".signin-mckinsey.com",
        ".skypeforbusiness.us",
        ".sli.do",
        ".slido.com",
        ".smartsheet.com",
        ".terrapower.com",
        ".ttec.com",
        ".usgovcloudapi.net",
        ".usgovtrafficmanager.net",
        ".welcometogehealthcare.com",
        ".windows.usgovcloud-static.microsoft",
        ".windows.usgovcloud.microsoft",
        ".wscf.us",
        "168.63.129.16",
        "169.254.169.254",
        "3dx-prod.sc.edf-energy.com",
        "63.80.119.*",
        "65.216.161.*",
        "66.161.236.245",
        "access.westernpower.com.au",
        "aeroline-crm.stengg.com",
        "aeroline-imedia-sg.stengg.com",
        "aeroline-imedia-us.stengg.com",
        "aeroline-test.stengg.com",
        "aeroline.stengg.com",
        "aerospace-dev.saviyntcloud.com",
        "agtm.sanayi.gov.tr",
        "api.teams.microsoft.us",
        "app.powerbi.us",
        "app.wiz.io",
        "autodiscover-51500.office365.us",
        "autodiscover-s.office365.us",
        "autodiscover.ge.onmicrosoft.us",
        "autodiscover.geaerospace.com",
        "autodiscover.geaerospace.us",
        "autodiscover.office365.us",
        "berwyn-address-search.com",
        "berwynaddresscheck.com",
        "bhgeqa.multibankportal.com",
        "bkrtradefinance.multibankportal.com",
        "bnet.nppd.com",
        "bsllcdocs.bollingershipyards.com",
        "cefswa.ubs.com",
        "cefswauat01.ubstest.com",
        "cevo.coned.com",
        "channelconnect.ge.com",
        "cloudfront.amazonaws.com",
        "compliance.microsoft.us",
        "conedison.cloud.com",
        "core.skywise.com",
        "csg.delta.com",
        "csrc-snd.predix.io",
        "csrc.predix.io",
        "dc-ge-integrations.s3.amazonaws.com",
        "dell-console.druva.com",
        "dell-login.druva.com",
        "dev-splunkforcloud.gepower.com",
        "dev.network.digital.geaviation.com",
        "downloads.mend.io",
        "e-katalog.lkpp.go.id",
        "endpoint.microsoft.us",
        "enterpriseenrollment.microsoft.us",
        "enterpriseregistration.us",
        "es.geavio.splunkcloud.com",
        "forms.office365.us",
        "ge-power-chiba-mill.maximo.com",
        "ge-vernova.pelico.io",
        "geaerospace.saviyntcloud.com",
        "geaerospacetpag-dev.saviyntcloud.com",
        "geaerospacetpag.saviyntcloud.com",
        "geamtexportsdev.blob.core.windows.net",
        "geamtexportsprod.blob.core.windows.net",
        "geamtexportsqa.blob.core.windows.net",
        "geamtfileuploadprd.blob.core.windows.net",
        "geaviationdigital-*.visualstudio.com",
        "geavio.splunkcloud.com",
        "gedmft.gevernova.com",
        "geh-dng.clm.ibmcloud.com",
        "geh-elmnonpe.clm.ibmcloud.com",
        "geh.3keysoft.us",
        "gehcsdwandev-703514.sdwan.cisco.com",
        "genea-dev.etq.com",
        "genea.etq.com",
        "gevernova-dev.saviyntcloud.com",
        "gevernova.saviyntcloud.com",
        "github.devtools.predix.io",
        "graph.microsoft.us",
        "grip.software.gevernova.com",
        "hdx.secure.snecma.fr",
        "inside.cytiva.com",
        "irpas.aia.co.th",
        "jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com",
        "lmtv.lmwindpower.com",
        "login.microsoftonline.us",
        "m4.ironmountain.at",
        "manage.microsoft.us",
        "media.teams.microsoft.us",
        "mevzuat.gov.tr",
        "mft.edfluminus.be",
        "myapps.upmc.edu",
        "net3-nuclear.snclavalin.com",
        "net3t-nuclear.snclavalin.com",
        "nfuse.delta.com",
        "outlook.office365.us",
        "outlook.office365.us.mcas-gov.us",
        "portal.azure.com",
        "portal.berwyngroup.com",
        "protection.office365.us",
        "qa1.network.digital.geaviation.com",
        "reports-phoenix.druva.com",
        "resmigazete.gov.tr",
        "rosewood-containers.palantircloud.com",
        "runway.tines.com",
        "saas.mend.io",
        "salaryplan.co.in",
        "search.berwyngroup.com",
        "secure-xfer.ubs.com",
        "secure.aadcdn.us",
        "secure.trioptima.com",
        "security.microsoft.us",
        "sites.media-server.com",
        "smtp.office365.us",
        "sofocle.gcasupply.com",
        "solutions.mckinsey.com",
        "sso.sanayi.gov.tr",
        "staging-accessops.westernpower.com.au",
        "standard.no",
        "teams.microsoft.us",
        "templates.office.com",
        "test.trioptima.com",
        "tines.apps.geaerospace.com",
        "tungsram-icon.mckinseywave.com",
        "vmi.datalliance.net",
        "wenshu.court.gov.cn",
        "www.bct.gov.tn",
        "www.cscfinancialonline.com",
        "www.lkpp.go.id",
        "www.yammer.us"
    ],
    //EndSendToZen

    // Destination Host which must go via regional proxy due to Local law or other proxies like GDC Parent Proxies
    SendToOtherProxy: [
        ".abstract.com",
        ".airtable.com",
        ".akamaihd.net",
        ".alight.com",
        ".amazonappstream.com",
        ".aperianglobal.com",
        ".api.microsoftstream.com",
        ".app11.jaggaer.com",
        ".appspot.com",
        ".azureedge.net",
        ".bl-1.com",
        ".bmc.cdn.office.net",
        ".boldchat.com",
        ".box.com",
        ".box.ge.com",
        ".box.net",
        ".boxcdn.net",
        ".boxcloud.com",
        ".broadcast.skype.com",
        ".cdn.office.net",
        ".cdn.optimizely.com",
        ".cloudapp.net",
        ".cobrowse.oraclecloud.com",
        ".concursolutions.com",
        ".connect.spglobal.com",
        ".console.aws.amazon.com",
        ".coupahost.com",
        ".custhelp.com",
        ".data.digitalassistant.oci.oraclecloud.com",
        ".doubleclick.net",
        ".ei.go.kr",
        ".fa.us2.oraclecloud.com",
        ".fidelity.com",
        ".fool.com",
        ".foolcdn.com",
        ".force.com",
        ".geaviation.com",
        ".gehealthcare.com",
        ".gesteampower.com",
        ".goabstract.com",
        ".google-analytics.com",
        ".google.com",
        ".google.com.sg",
        ".googleadservices.com",
        ".googleapis.com",
        ".googlesyndication.com",
        ".googletagmanager.com",
        ".googletagservices.com",
        ".gov.teams.microsoft.us",
        ".gstatic.com",
        ".iconfinder.com",
        ".inform-ams.com",
        ".kollective.app",
        ".livelook.com",
        ".mapadore.com",
        ".marketo.com",
        ".media.azure.net",
        ".msecnd.net",
        ".mypurecloud.com",
        ".officeapps.live.com",
        ".performancemanager8.successfactors.com",
        ".pixaera.com",
        ".powersource.gsinc.com",
        ".qualtrics.com",
        ".rightnowtech.com",
        ".rtccloud.net",
        ".salesforce.com",
        ".seismic.com",
        ".sightcall.com",
        ".sli.do",
        ".smartsheet.com",
        ".streaming.mediaservices.windows.net",
        ".suralink.com",
        ".surveymonkey.co.uk",
        ".surveymonkey.com",
        ".teams.microsoft.com",
        ".veeva.link",
        ".veevavault.com",
        ".vimana.us",
        ".vimeo.com",
        ".weforum.org",
        ".wistia.com",
        "24.24.24.24",
        "IAta.org",
        "abb-epis.gensuite.com",
        "account.realitycharting.com",
        "adobeid-na1.services.adobe.com",
        "aerospace.edcast.com",
        "ajax.aspnetcdn.com",
        "aka.ms",
        "api.kiuey.com",
        "api.ppapmanager.com",
        "app-uai3062831-dhr-dbc-prd-s3-bucket.s3-accelerate.amazonaws.com",
        "app.aperian.com",
        "app.getmaintainx.com",
        "app.landing.ai",
        "app.safetyculture.io",
        "app.sc.ge.com",
        "app11.jaggaer.com",
        "assets.adobedtm.com",
        "ast.gehealthcare.com",
        "auth.boeing.com",
        "authenticator.pingone.com",
        "authenticator.pingone.eu",
        "bh-app.alfrescocloud.com",
        "bh.alfrescocloud.com",
        "bhge.gensuite.com",
        "box.ge.myshn.net",
        "cdn.aperian.com",
        "cdn.auth0.com",
        "cdn.complyworks.com",
        "cdn.prod.betterup.co",
        "cdn.sstatic.net",
        "cdn.walkme.com",
        "cdnjs.cloudflare.com",
        "china.usembassy-china.org.cn",
        "clarity.gehc.moventus.com",
        "cloud.workhuman.com",
        "cms.securimate.com",
        "code.jquery.com",
        "compass.astm.org",
        "confluence-connect.gliffy.net",
        "consent.app.relyance.ai",
        "crl.usertrust.com",
        "cytiva.gensuite.com",
        "d2d6mu5qcvgbk5.cloudfront.net",
        "d758cqe2bs24d.cloudfront.net",
        "dhl.com",
        "dleeflex.auth.us-east-2.amazoncognito.com",
        "download.01.org",
        "edcf.fs.em2.oraclecloud.com",
        "edge.media-server.com",
        "email.safetyculture.io",
        "enhk-dev1.fa.em3.oraclecloud.com",
        "expeditors.com",
        "fedex.com",
        "file.connect.ihsmarkit.com",
        "fobsis.fos4x.de",
        "fonts.geapps.io",
        "ge.benchmarkdigital.com",
        "ge.gensuite.com",
        "ge.novoed.com",
        "ge.sumtotal.host",
        "ge.sumtotalsystems.com",
        "geaerospace.edcast.com",
        "gegaspower-buyerportal.coraapflow.com",
        "gehc-ast-prod.pegacloud.net",
        "gehc-pqm.pegacloud.net",
        "gehc-prod.ptcmanaged.com",
        "gehc-torusholds.pegacloud.net",
        "gehealthcare.showpad.biz",
        "gehealthcaresandbox.showpad.biz",
        "geit.service-now.com",
        "geportal-sso.sumtotalsystems.com",
        "geportal.sumtotalsystems.com",
        "gepower-uat.herokuapp.com",
        "geren-buyerportal.coraapflow.com",
        "gerenewsopilmw.o9solutions.com",
        "gevernova.edcast.com",
        "gevernova.vndly.com",
        "go.microsoft.com",
        "hcmcloud.excelityglobal.com",
        "hpi.quickbase.com",
        "idcs-e856d7ab5be746c3b28b37117af1a507.identity.oraclecloud.com",
        "idcs-f0dc0d071f1142678ed8f1b1e783d212.identity.oraclecloud.com",
        "identity.sae.org",
        "idm-reg01.j1p.jaggaer.com",
        "idp.workhuman.com",
        "img-s-msn-com.akamaized.net",
        "ims-na1.adobelogin.com",
        "internalcareers.gevernova.com",
        "js.intercomcdn.com",
        "keysight.com",
        "lighting.gensuite.com",
        "login.phenom.com",
        "manifest.prod.boltdns.net",
        "matplotlib.org",
        "maxcdn.bootstrapcdn.com",
        "metrics.brightcove.com",
        "miro.com",
        "mirostatic.com",
        "molex.com",
        "mouser.com",
        "msteamsstatics.blob.core.usgovcloudapi.net",
        "mta-app-ui.azurewebsites.net",
        "new.complyworks.com",
        "ocsp.usertrust.com",
        "ok6static.oktacdn.com",
        "onsemi.com",
        "oobe.adobe.com",
        "players.brightcove.net",
        "pmx.gepower.com",
        "products.office.com",
        "pypi.org",
        "r3.res.outlook.com",
        "rally1.rallydev.com",
        "s3-eu-central-1.amazonaws.com",
        "sae-public-css.cld.sae.org",
        "saemobilus.sae.org",
        "sapui5.hana.ondemand.com",
        "secure.astm.org",
        "secure.entertimeonline.com",
        "secure4.entertimeonline.com",
        "services.gehealthcare.cn",
        "shannonenginesupport.cake.hr",
        "signin.aws.amazon.com",
        "smartshop.gepower.com",
        "software.intel.com",
        "ssl2.perquisite.net",
        "sso.konectar.io",
        "ssogen.gecompany.com",
        "stackoverflow.com",
        "stackpath.bootstrapcdn.com",
        "static-global-s-msn-com.akamaized.net",
        "static-website.miro.com",
        "static.talentlms.com",
        "static2.sharepointonline.com",
        "statics.teams.microsoft.com",
        "support.oracle.com",
        "tasks.office.com",
        "teamsapuiwebcontent.blob.core.usgovcloudapi.net",
        "tejoin.com",
        "wam.apps.ge.com",
        "web.cvent.com",
        "web.microsoftstream.com",
        "www.airtable.com",
        "www.bluetooth.com",
        "www.caas.gov.sg",
        "www.complyworks.com",
        "www.ge.com",
        "www.gebrandcentral.com",
        "www.getabstract.com",
        "www.metricsthatmatter.com",
        "www.microsoft.com",
        "www.rnengage.com",
        "www.tensorflow.org",
        "www.ubs.com",
        "xilinx.com"
    ],
    //EndSendToOtherProxy

    SendToOtherProxy2: [
        // As adblock
        ".sanalytics.box.com",
        ".pendo-data-prod.box.com",
        ".pendo-prod.box.com",
        ".box.demdex.net",
        ".dpm.demdex.net",
        ".client-log.box.com",
        ".analytics.box.com",
        ".track.box.com",
        // https://github.com/cbuijs/hagezi/blob/main/lists/native-winoffice/domains
        ".a-ring-fallback.msedge.net",
        ".a-ring.msedge.net",
        ".a4.bing.com",
        ".ac2.msn.com",
        ".activity.windows.com",
        ".ad.msn.com",
        ".adevents.msn.com",
        ".ads-msn-com-profile.trafficmanager.net",
        ".ads.bing.com",
        ".ads.eu.msn.com",
        ".ads.jp.msn.com",
        ".ads.microsoft.com",
        ".ads.msn.com",
        ".ads1.msn.com",
        ".adsdk.microsoft.com",
        ".adsdk.trafficmanager.net",
        ".adsdkpreprod.afd.azureedge.net",
        ".adsdkpreprod.azureedge.net",
        ".adsdkprod.afd.azureedge.net",
        ".adsdkprod.azureedge.net",
        ".adserver.bing.com",
        ".adstore.response.gcp.eastus.trafficmanager.net",
        ".advertising.jp.msn.com",
        ".advertising.microsoft.com",
        ".agps-location-livenet.trafficmanager.net",
        ".analytics-dev-lleap-events.servicebus.windows.net",
        ".analytics-dev-simpad-events.servicebus.windows.net",
        ".analytics-listener.trafficmanager.net",
        ".analytics.live.com",
        ".analytics.msnbc.msn.com",
        ".analytics.trafficmanager.net",
        ".analyticsehnwe.servicebus.windows.net",
        ".analyticspixel.microsoft.com",
        ".api.applicationinsights.azure.cn",
        ".api.edgeoffer.microsoft.com",
        ".applicationinsights.azure.com",
        ".applicationinsights.microsoft.com",
        ".arc-emea.msn.com",
        ".arc.msn.com",
        ".arc1.msn.com",
        ".arc2.msn.com",
        ".arc3.msn.com",
        ".arc5.msn.com",
        ".arc9.msn.com",
        ".auc-visio-telemetry.officeapps.live.com",
        ".az667904.vo.msecnd.net",
        ".azurewatson.microsoft.com",
        ".azurewatsontest.microsoft.com",
        ".b-ring-fallback.msedge.net",
        ".b-ring.msedge.net",
        ".bat.bing.com",
        ".bat.r.msn.com",
        ".beacons.trafficmanager.net",
        ".beacons.xboxlive.com",
        ".bingads.microsoft.com",
        ".bingads.trafficmanager.net",
        ".brc-visio-telemetry.officeapps.live.com",
        ".c-bingapis-com.dual-a-0034.a-msedge.net",
        ".c-ring-fallback.msedge.net",
        ".c-ring.msedge.net",
        ".c.ar.msn.com",
        ".c.at.msn.com",
        ".c.be.msn.com",
        ".c.bing.com",
        ".c.bingapis.com",
        ".c.br.msn.com",
        ".c.ca.msn.com",
        ".c.cl.msn.com",
        ".c.de.msn.com",
        ".c.dk.msn.com",
        ".c.es.msn.com",
        ".c.fi.msn.com",
        ".c.fr.msn.com",
        ".c.gr.msn.com",
        ".c.hk.msn.com",
        ".c.id.msn.com",
        ".c.ie.msn.com",
        ".c.il.msn.com",
        ".c.in.msn.com",
        ".c.it.msn.com",
        ".c.jp.msn.com",
        ".c.latam.msn.com",
        ".c.live.com",
        ".c.my.msn.com",
        ".c.nl.msn.com",
        ".c.no.msn.com",
        ".c.ph.msn.com",
        ".c.prodigy.msn.com",
        ".c.pt.msn.com",
        ".c.ru.msn.com",
        ".c.se.msn.com",
        ".c.sg.msn.com",
        ".c.th.msn.com",
        ".c.tr.msn.com",
        ".c.tw.msn.com",
        ".c.uk.msn.com",
        ".c.xbox.com",
        ".c.za.msn.com",
        ".c1.microsoft.com",
        ".cac-visio-telemetry.officeapps.live.com",
        ".cache.datamart.windows.com",
        ".ceuswatcab01.blob.core.windows.net",
        ".ceuswatcab02.blob.core.windows.net",
        ".ch-asimov-leafs-events-data.trafficmanager.net",
        ".chc-visio-telemetry.officeapps.live.com",
        ".citrixanalyticseh-alias.servicebus.windows.net",
        ".citrixanalyticseh.servicebus.windows.net",
        ".citrixanalyticseh2-alias.servicebus.windows.net",
        ".citrixanalyticseh3-alias.servicebus.windows.net",
        ".citrixanalyticseh3.servicebus.windows.net",
        ".citrixanalyticsehaps-alias.servicebus.windows.net",
        ".citrixanalyticsehaps.servicebus.windows.net",
        ".citrixanalyticseheu-alias.servicebus.windows.net",
        ".citrixanalyticseheu.servicebus.windows.net",
        ".citrixtelemetryeh-alias.servicebus.windows.net",
        ".citrixtelemetryeh.servicebus.windows.net",
        ".citrixtelemetryeheu-alias.servicebus.windows.net",
        ".citrixtelemetryeheu.servicebus.windows.net",
        ".cjs-diagnostics-office-com-gvdhgwfwbbfsd9g3.z01.azurefd.net",
        ".clarity.microsoft.com",
        ".collection-location-livenet.trafficmanager.net",
        ".collector-main.trafficmanager.net",
        ".collector.azure.cn",
        ".collector.azure.eaglex.ic.gov",
        ".collector.azure.microsoft.cloud",
        ".commerce.bing.com",
        ".confiant.msn.com",
        ".dc.applicationinsights.azure.cn",
        ".dc.applicationinsights.azure.us",
        ".dc.services.visualstudio.com",
        ".dec-visio-telemetry.officeapps.live.com",
        ".diagnostics-eudb.office.com",
        ".diagnostics.office.com",
        ".dsp-ad-cache-tm.trafficmanager.net",
        ".dual-s-ring.msedge.net",
        ".eaus2watcab01.blob.core.windows.net",
        ".eaus2watcab02.blob.core.windows.net",
        ".ehtelemetrystaging-alias.servicebus.windows.net",
        ".euc-excel-telemetry.officeapps.live.com",
        ".euc-excel-telemetry.wac.trafficmanager.net",
        ".euc-onenote-telemetry.officeapps.live.com",
        ".euc-powerpoint-telemetry.officeapps.live.com",
        ".euc-powerpoint-telemetry.wac.trafficmanager.net",
        ".euc-visio-telemetry.officeapps.live.com",
        ".euc-word-telemetry.officeapps.live.com",
        ".euc-word-telemetry.wac.trafficmanager.net",
        ".eurffc-word-telemetry.officeapps.live.com",
        ".eurffc-word-telemetry.wac.trafficmanager.net",
        ".eurppc-excel-telemetry.officeapps.live.com",
        ".eurppc-powerpoint-telemetry.officeapps.live.com",
        ".eurppc-word-telemetry.officeapps.live.com",
        ".events-sandbox.data.microsoft.com",
        ".events-sandbox.data.msn.com",
        ".events.data.microsoft.com",
        ".events.data.msn.cn",
        ".events.data.msn.com",
        ".events.data.trafficmanager.net",
        ".eventservice.trafficmanager.net",
        ".excel-telemetry.officeapps.live.com",
        ".excel-telemetry.wac.trafficmanager.net",
        ".excelonline.nel.measure.office.net.cardano.com",
        ".exo.nel.measure.office.net.cardano.com",
        ".ffc-excel-telemetry.officeapps.live.com",
        ".ffc-word-telemetry.officeapps.live.com",
        ".ffg-analyticsk3nvxfne4dp4s.servicebus.windows.net",
        ".fgteu1-word-telemetry-vip.officeapps.live.com",
        ".flex.msn.com",
        ".fp.msedge.net",
        ".frc-visio-telemetry.officeapps.live.com",
        ".g.bing.com",
        ".g00.msn.com",
        ".gateway.bingviz.microsoftapp.net",
        ".ghochv3eng.trafficmanager.net",
        ".glance-analytics.trafficmanager.net",
        ".h1.msn.com",
        ".h2.msn.com",
        ".h4g3z1-native.winoffice.web.app",
        ".h6.msn.com",
        ".hk-tracker.trafficmanager.net",
        ".hme-live-loganalytics-namespace.servicebus.windows.net",
        ".hme-uat-loganalytics-namespace.servicebus.windows.net",
        ".i1.services.social.microsoft.com",
        ".identity.nel.measure.office.net.cardano.com",
        ".ieonline.microsoft.com",
        ".in.appcenter.ms",
        ".in.applicationinsights.azure.cn",
        ".in.applicationinsights.azure.us",
        ".inc-visio-telemetry.officeapps.live.com",
        ".inference-app-gateway.eastus2.cloudapp.azure.com",
        ".inference-app-gateway.koreacentral.cloudapp.azure.com",
        ".inference-app-gateway.northeurope.cloudapp.azure.com",
        ".inference-location-livenet.trafficmanager.net",
        ".ingest.appcenter.ms",
        ".insights.cloud.microsoft",
        ".ir-tracking.trafficmanager.net",
        ".irreverselookuptm.trafficmanager.net",
        ".ism-telemetry.trafficmanager.net",
        ".js.cdn.applicationinsights.io",
        ".js.monitor.azure.com",
        ".js0.cdn.applicationinsights.io",
        ".js0.tst.applicationinsights.io",
        ".js1.cdn.applicationinsights.io",
        ".js1.tst.applicationinsights.io",
        ".js2.cdn.applicationinsights.io",
        ".js2.tst.applicationinsights.io",
        ".k-ring-fallback.msedge.net",
        ".k-ring.msedge.net",
        ".kg-legacy-analytics.servicebus.windows.net",
        ".legacywatson.trafficmanager.net",
        ".licensingtelemetry-prod.servicebus.windows.net",
        ".ln-ring-fallback.msedge.net",
        ".ln-ring.msedge.net",
        ".location-microsoft-com.b-0005.b-msedge.net",
        ".location.live.net",
        ".location.microsoft.com",
        ".m365cdn.nel.measure.office.net.cardano.com",
        ".measure.office.com",
        ".measure.office.com.akamaized.net",
        ".measure.office.net",
        ".measure.office.net.edgesuite.net",
        ".metric.appex-rf.msn.com",
        ".mobileads.msn.com",
        ".mobileleads.msn.com",
        ".msads.net",
        ".msadsscale.azureedge.net",
        ".msadsscale.microsoft.com",
        ".nexus.officeapps.live.com",
        ".nexusrules.live.com",
        ".nexusrules.officeapps.live.com",
        ".nexxtv-events.servicebus.windows.net",
        ".noc-visio-telemetry.officeapps.live.com",
        ".o.xbox.com",
        ".oca.microsoft.com",
        ".office-events-data.trafficmanager.net",
        ".officehub.nel.measure.office.net.cardano.com",
        ".oms-analytics.trafficmanager.net",
        ".outlookads.live.com",
        ".pgtbr1-excel-telemetry-vip.officeapps.live.com",
        ".pgtbr1-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtbr1-word-telemetry-vip.officeapps.live.com",
        ".pgtbr2-excel-telemetry-vip.officeapps.live.com",
        ".pgtbr2-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtbr2-word-telemetry-vip.officeapps.live.com",
        ".pgtca1-excel-telemetry-vip.officeapps.live.com",
        ".pgtca1-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtca1-word-telemetry-vip.officeapps.live.com",
        ".pgteu1-excel-telemetry-vip.officeapps.live.com",
        ".pgteu1-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgteu1-word-telemetry-vip.officeapps.live.com",
        ".pgteu2-excel-telemetry-vip.officeapps.live.com",
        ".pgteu2-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgteu2-word-telemetry-vip.officeapps.live.com",
        ".pgteu3-excel-telemetry-vip.officeapps.live.com",
        ".pgteu3-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgteu3-word-telemetry-vip.officeapps.live.com",
        ".pgteu4-excel-telemetry-vip.officeapps.live.com",
        ".pgteu4-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgteu4-word-telemetry-vip.officeapps.live.com",
        ".pgteu5-excel-telemetry-vip.officeapps.live.com",
        ".pgteu5-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgteu5-word-telemetry-vip.officeapps.live.com",
        ".pgtmx1-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtmx1-word-telemetry-vip.officeapps.live.com",
        ".pgtus1-excel-telemetry-vip.officeapps.live.com",
        ".pgtus1-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus1-word-telemetry-vip.officeapps.live.com",
        ".pgtus2-excel-telemetry-vip.officeapps.live.com",
        ".pgtus2-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus2-word-telemetry-vip.officeapps.live.com",
        ".pgtus3-excel-telemetry-vip.officeapps.live.com",
        ".pgtus3-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus3-word-telemetry-vip.officeapps.live.com",
        ".pgtus4-excel-telemetry-vip.officeapps.live.com",
        ".pgtus4-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus4-word-telemetry-vip.officeapps.live.com",
        ".pgtus5-excel-telemetry-vip.officeapps.live.com",
        ".pgtus5-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus5-word-telemetry-vip.officeapps.live.com",
        ".pgtus6-excel-telemetry-vip.officeapps.live.com",
        ".pgtus6-powerpoint-telemetry-vip.officeapps.live.com",
        ".pgtus6-word-telemetry-vip.officeapps.live.com",
        ".pipe.aria.microsoft.com",
        ".pixel-sync.trafficmanager.net",
        ".popup.msn.com",
        ".powerpoint-telemetry.officeapps.live.com",
        ".powerpoint-telemetry.wac.trafficmanager.net",
        ".ppc-excel-telemetry.officeapps.live.com",
        ".ppc-excel-telemetry.wac.trafficmanager.net",
        ".ppc-onenote-telemetry.officeapps.live.com",
        ".ppc-powerpoint-telemetry.officeapps.live.com",
        ".ppc-powerpoint-telemetry.wac.trafficmanager.net",
        ".ppc-word-telemetry.officeapps.live.com",
        ".ppc-word-telemetry.wac.trafficmanager.net",
        ".ppm-licensingtelemetry.servicebus.windows.net",
        ".preview.msn.com",
        ".prod-eh-v1-analytics.servicebus.windows.net",
        ".prod-eventhub-analytics.servicebus.windows.net",
        ".prod.editor.ads.trafficmanager.net",
        ".production-jobactivity-analytics.servicebus.windows.net",
        ".rad.live.com",
        ".rad.microsoft.com",
        ".rads.msn.com",
        ".raka.bing.com",
        ".rawtelemetry-east.servicebus.windows.net",
        ".rawtelemetry-west.servicebus.windows.net",
        ".redir.metaservices.microsoft.com",
        ".rel.msn.com",
        ".rmads.eu.msn.com",
        ".rmads.msn.com",
        ".s-ring-fallback.msedge.net",
        ".s-ring.msedge.net",
        ".sa.windows.com",
        ".sam.msn.com",
        ".self-events-data.trafficmanager.net",
        ".sgtus1-excel-telemetry-vip.officeapps.live.com",
        ".sgtus1-powerpoint-telemetry-vip.officeapps.live.com",
        ".sgtus1-word-telemetry-vip.officeapps.live.com",
        ".spo.nel.measure.office.net.cardano.com",
        ".spynet2.microsoft.com",
        ".spynetalt.microsoft.com",
        ".srtb.msn.com",
        ".ss-telemetry.servicebus.windows.net",
        ".ssp-prod-eastus-nonmutt.trafficmanager.net",
        ".ssw.live.com",
        ".stats-partner.trafficmanager.net",
        ".statsfe1.ws.microsoft.com",
        ".statsfe2.ws.microsoft.com",
        ".stjjp.msn.com",
        ".swiftanalyticsprod.servicebus.windows.net",
        ".t-ring-fallback-s2.msedge.net",
        ".t-ring-fallback.msedge.net",
        ".t-ring-fallbacks1.msedge.net",
        ".t-ring-fallbacks2.msedge.net",
        ".t-ring-fdv2.msedge.net",
        ".t-ring-s.msedge.net",
        ".t-ring-s2.msedge.net",
        ".t-ring-trafficshield.msedge.net",
        ".t-ring.msedge.net",
        ".t-s1-ring.msedge.net",
        ".t-s2-ring.msedge.net",
        ".teams-events-data.trafficmanager.net",
        ".teams.nel.measure.office.net.cardano.com",
        ".telecommandsvc.microsoft.com",
        ".telem-edge.smartscreen.microsoft.com",
        ".telemetry-lcp.trafficmanager.net",
        ".telemetry.eastus.trafficmanager.net",
        ".telemetry.microsoft.com",
        ".telemetry.microsoft.us",
        ".telemetry.officeapps.live.com",
        ".telemetry.urs.microsoft.com",
        ".telemetry.visualstudio.microsoft.com",
        ".telemetrycollector.microsoft.com",
        ".tgtus1-excel-telemetry-vip.officeapps.live.com",
        ".tgtus1-powerpoint-telemetry-vip.officeapps.live.com",
        ".tgtus1-word-telemetry-vip.officeapps.live.com",
        ".tm-analytics-pr.trafficmanager.net",
        ".tm-enrollment-telemetry-datacore.trafficmanager.net",
        ".toolbar.msn.com",
        ".track.mp.microsoft.com",
        ".track.notif.careersppe.microsoft.com",
        ".tracker.flightview.com.trafficmanager.net",
        ".udc.msn.com",
        ".ukc-onenote-telemetry.officeapps.live.com",
        ".ukc-visio-telemetry.officeapps.live.com",
        ".us-mesh-events-data-leafs.trafficmanager.net",
        ".usc-onenote-telemetry.officeapps.live.com",
        ".usc-visio-telemetry.officeapps.live.com",
        ".utm.sankei.jp.msn.com",
        ".visio-telemetry.officeapps.live.com",
        ".vortex-sandbox.data.microsoft.com",
        ".vortex-win-sandbox.data.microsoft.com",
        ".vortex-win.data.microsoft.com",
        ".vortex.data.microsoft.com",
        ".vortex.data.trafficmanager.net",
        ".vstelemetry.trafficmanager.net",
        ".watson.live.com",
        ".watson.microsoft.com",
        ".watson.officeint.microsoft.com",
        ".wayfinderanalytics.servicebus.windows.net",
        ".westeurope-5.in.applicationinsights.azure.com.fiege.de",
        ".weus2watcab01.blob.core.windows.net",
        ".weus2watcab02.blob.core.windows.net",
        ".win-global-asimov-leafs-events-data.trafficmanager.net",
        ".win10-trt.msedge.net",
        ".word-telemetry.officeapps.live.com",
        ".word-telemetry.wac.trafficmanager.net",
        ".wttwebsiteprodapi-liveevents.trafficmanager.net",
        ".zmetrics.msn.com"
    ],
    //EndSendToOtherProxy2

    // Default rule sends everything to proxy, Some Hosts may be hosted on external webservers
    // and needs to go via Proxy - Ex. www.ge.com, Such exceptions goes here
    SendToProxy: [
        "*cqd.lync.com",
        "apps.converteam.com",
        "autodiscover.cytiva.com",
        "autodiscover.gecompany.mail.onmicrosoft.com",
        "autodiscover.ipce.broadcom.com",
        "autodiscover.techmahindra.com",
        "autodiscover.techmahindra.mail.onmicrosoft.com",
        "autodiscover.wayne.com",
        "careers.converteam.com",
        "catalogs.datex-ohmeda.com",
        "citrix.converteam.com",
        "clarientinc.com",
        "cms.whatman.com",
        "critikon.com",
        "csn111svgweb2.corp.dresser.com",
        "dpintnotes01.dresser.eu",
        "emplois.converteam.com",
        "eur.sabic-ip.com",
        "ge.com.mx",
        "ge.ramco.com",
        "gehealthcare.net",
        "genpact.com",
        "gesm.osmonics.com",
        "go.additive.ge.com",
        "iimaging.com",
        "karriere.converteam.com",
        "lunarcorp.com",
        "meridium.com",
        "millbrook.com",
        "my.osmonics.com",
        "mydfts.corp.dresser.com",
        "mymasoneilan.corp.dresser.com",
        "osmonics.com",
        "pcb.converteam.com",
        "photolibrary.converteam.com",
        "pmi-saas-emea.cegedim.com",
        "portal.doosan.com",
        "saab.saabdealer.org",
        "sc.1utcfs.com",
        "secure-transfer.cegedim.com",
        "secure.millbrook.com",
        "servicecenter.firstdataclients.com",
        "shop.osmonics.com",
        "signature-cegepass.cegedim.com",
        "signature-ceremony.cegedim.com",
        "spo-admin.ge.com",
        "spo-mydrive.ge.com",
        "spo-teamsite.ge.com",
        "stg-catalogs.datex-ohmeda.com",
        "stg-secure.millbrook.com",
        "storage-eb4.cloud.cegedim.com",
        "stspublic.cegedim.com",
        "supportcentral.1utcfs.com",
        "tripleg.com",
        "tripleg.com.au",
        "tsgateway1.meridium.com",
        "values.photochallenge.converteam.com",
        "webvpn.doosan.com",
        "webvpn.meridium.com",
        "webvpn1.doosan.com",
        "webvpn2.doosan.com",
        "webvpn3.doosan.com",
        "whatman.com",
        "www.amersham.co.uk",
        "www.amersham.com",
        "www.apbiotech.com",
        "www.api.com",
        "www.applicare.com",
        "www.avio.net",
        "www.cat-rewards.firstdataclients.com",
        "www.cegedim-srh.com",
        "www.converteam.com",
        "www.datex-ohmeda.com",
        "www.doosan.com",
        "www.firstdataclients.com",
        "www.gesm.osmonics.com",
        "www.golfchannel.com",
        "www.instru.net",
        "www.instrumentarium.fi",
        "www.ionics.com",
        "www.mdyn.com",
        "www.meridium.com",
        "www.mft3.firstdataclients.com",
        "www.my.osmonics.com",
        "www.nycomed-amersham.com",
        "www.osmonics.com",
        "www.prucka.com",
        "www.rewards.firstdataclients.com",
        "www.tripleg.com"
    ],
    //EndSendToProxy

    // GE Internal Domains and Hosts goes here
    DoNotSendToProxy: [
        "*.opc.oracleoutsourcing.com",
        "*ariba.smiths.com",
        "*intranet.smiths.com",
        "*lc.smiths.com",
        "*legal-compliance.smiths.com",
        "*mpc.smiths.com",
        "*mpcreports.smiths.com",
        "*ori.gemoney.ru",
        "*oriuat.gemoney.ru",
        "*oriuat2.gemoney.ru",
        "*pdq.gesdgodc.com",
        "*smiths.aero",
        ".1dc.com",
        ".1utcfs.com",
        ".ad.innio.com",
        ".ad.sys",
        ".adf.azure.com",
        ".aercap.corp",
        ".aero.bombardier.net",
        ".afs.azure.net",
        ".agentsvc.azure-automation.net",
        ".airbus.corp",
        ".alstom.com",
        ".amazonaws.com",
        ".amersham.co.uk",
        ".amersham.com",
        ".amr.sabic-ip.com",
        ".apac.sabic-ip.com",
        ".apbiotech.com",
        ".api-wi.com",
        ".api.com",
        ".applicare.com",
        ".apps.tungsram.com",
        ".areva-td.com",
        ".atd.corp",
        ".au.daintree.net",
        ".avio.net",
        ".avio.us",
        ".avioaero.net",
        ".aviousa.com",
        ".aws-tungsram.com",
        ".aws.innio.com",
        ".azconfig.io",
        ".azure-automation.net",
        ".azure-devices.net",
        ".azurecr.io",
        ".azuresynapse.net",
        ".azurewebsites.net",
        ".bankrc.local",
        ".batch.azure.com",
        ".bhicorp.com",
        ".bhinet.com",
        ".bkmedical.com",
        ".bkrh.oracleoutsourcing.com",
        ".blob.core.windows.net",
        ".boxlocalhost.com",
        ".bph.conpeek.com",
        ".bph.corp",
        ".bps2cust.com",
        ".cassandra.cosmos.azure.com",
        ".cegedim-srh.com",
        ".cegedim.com",
        ".cfsam.com",
        ".chromavision.int",
        ".clarientinc.com",
        ".commerce.reuters.com",
        ".connectsyf.com",
        ".converteam.com",
        ".corp.dresser.com",
        ".corp.xignux.com",
        ".critikon.com",
        ".cytiva.com",
        ".cytiva.net",
        ".danaher.org",
        ".data.gevernova.com",
        ".database.windows.net",
        ".datafactory.azure.net",
        ".datex-ohmeda.com",
        ".dd",
        ".dev.azuresynapse.net",
        ".dfs.core.windows.net",
        ".dfs.na.deuba.com",
        ".digitaltwins.azure.net",
        ".documents.azure.com",
        ".doosan.com",
        ".doosanenc.com",
        ".dresser.com",
        ".dresser.eu",
        ".dtc1.fr.td.sys",
        ".elasticbeanstalk.com",
        ".elgems.com",
        ".eme.sys",
        ".emea.sabic-ip.com",
        ".emrmas.org",
        ".esca.com",
        ".eur.sabic-ip.com",
        ".eventgrid.azure.net",
        ".fieldcoreapps.com",
        ".file.core.windows.net",
        ".firstdataclients.com",
        ".fxb.npi",
        ".gccc.sabic-ip.com",
        ".ge-alstomenergy.com",
        ".ge-healthcare.net",
        ".ge.com",
        ".ge.com.mx",
        ".ge.ramco.com",
        ".geae.com",
        ".geaerospace.net",
        ".geam.blackrock.com",
        ".geblue.net",
        ".gecdn.com",
        ".gecurrent.net",
        ".gefadigitaloffice.com",
        ".gefdl-dev.ey.com",
        ".gefdl-qa.ey.com",
        ".gefdl.ey.com",
        ".gegdc.ad",
        ".gehealthcare.net",
        ".gemse.fr",
        ".genworth.net",
        ".gevernova-dyn.net",
        ".gevernova-stat.net",
        ".gevernova.net",
        ".global.ad",
        ".global.sabic-ip.com",
        ".golfchannel.com",
        ".green.local",
        ".gremlin.cosmos.azure.com",
        ".gs-inc.com",
        ".gs-int.com",
        ".ibhge.com",
        ".iderms.us",
        ".idm.sabic-ip.com",
        ".idmnet.org",
        ".igategegdc.com",
        ".iimaging.com",
        ".ikon.org",
        ".ilx.net",
        ".instru.net",
        ".instrumentarium.fi",
        ".int.atlas.gridos.com",
        ".intranet.genpact.com",
        ".intranet.mymoneybank.fr",
        ".ionics.com",
        ".ip",
        ".iso-ne.net",
        ".it2cust.com",
        ".jenbach.jenbacher",
        ".lan",
        ".lmglasfiber.com",
        ".lmwindpower.com",
        ".local",
        ".localhost",
        ".lufkin.france",
        ".lunarcorp.com",
        ".lync.com",
        ".managedhsm.azure.net",
        ".mariadb.database.azure.com",
        ".markets.reuters.com",
        ".mdyn.com",
        ".media.azure.net",
        ".mei.com",
        ".meridium.com",
        ".mgmt.com",
        ".millbrook.com",
        ".mongo.cosmos.azure.com",
        ".monitor.azure.com",
        ".myclarient.com",
        ".mymoney.intranet",
        ".mysofi.intranet",
        ".mysql.database.azure.com",
        ".mytungsram.com",
        ".na.ikon.net",
        ".nycomed-amersham.com",
        ".oci.innio.com",
        ".ods.opinsights.azure.com",
        ".oms.opinsights.azure.com",
        ".on.aws",
        ".oneprolec.net",
        ".oraclevcn.com",
        ".osmonics.com",
        ".oxygen.corp",
        ".oxygentv.corp",
        ".pdx.medicalogic.com",
        ".peoplepro.xignux.com",
        ".pii-uk.com",
        ".piipipelinesolutions.com",
        ".pjm.esca",
        ".polarisdealers.com",
        ".polarisind.com",
        ".polarisindustries.com",
        ".prod.migration.windowsazure.com",
        ".prolec.one",
        ".prolec.xignux.com",
        ".prolecge.com",
        ".prolecge.prolec.xignux.com",
        ".proxyge.com",
        ".prucka.com",
        ".purview.azure.com",
        ".purviewstudio.azure.com",
        ".pwcinternal.com",
        ".pwrsyst.com",
        ".pwsigner.ark-teknoloji.com",
        ".rationalalmus.geaviation.com",
        ".redis.cache.windows.net",
        ".redisenterprise.cache.azure.net",
        ".resource.corp",
        ".ricohonline.net",
        ".ricohus.org",
        ".rservices.com",
        ".rtextrading.reuters.com",
        ".rubenhoward.com",
        ".saabdealer.org",
        ".savanthome.net",
        ".sbic.sbicard.com",
        ".sclnet.com",
        ".search.windows.net",
        ".service.signalr.net",
        ".servicebus.windows.net",
        ".services.instinet.com",
        ".sip.reuters.net",
        ".siterecovery.windowsazure.com",
        ".sl.ge",
        ".smartsignal.us",
        ".smiths.aero",
        ".sppmosdev.org",
        ".sppmplusdev.org",
        ".sql.azuresynapse.net",
        ".stg-tfayd.com",
        ".supplier.prolec.energy",
        ".supportcentral.gesupply.com",
        ".supportcentral.sabic-ip.com",
        ".table.cosmos.azure.com",
        ".tayfd.com",
        ".tcsgegdc.com",
        ".test.reuters.com",
        ".tfayd.com",
        ".transformadores.xignux.com",
        ".tripleg.com",
        ".tripleg.com.au",
        ".us.ricoh.ds",
        ".usacable.net",
        ".usanetworks.com",
        ".vault.azure.net",
        ".vaultcore.azure.net",
        ".vetco.com",
        ".vetcogray.com",
        ".vetcogray.no",
        ".vmwarevmc.com",
        ".whatman.com",
        ".wpcorpnet.com",
        ".wpcorptest.com",
        ".wpextnet.com",
        ".wpmfgnet.com",
        ".wpsmi.com",
        ".wpxlab.com",
        ".xtra.reuters.com",
        ".xynet.net",
        ".zenotrac.com",
        "aca-client.axeda.com",
        "adfs.geappliances.com",
        "agileplmprod.bkmedical.com",
        "ak.bakerhughes.com",
        "artrg.nzta.govt.nz",
        "as-vault-corella.ren.apps.gevernova.com",
        "askalta-prd-com.azurewebsites.net",
        "askalta-prd-com2.azurewebsites.net",
        "auohsclib01.us.oracle.com",
        "auohsgeca30.oracleoutsourcing.com",
        "auohsgeca47.oracleoutsourcing.com",
        "auohsgeca69.oracleoutsourcing.com",
        "auohsgewr01.oracleoutsourcing.com",
        "auohsgewr02.oracleoutsourcing.com",
        "auohsgewr03.oracleoutsourcing.com",
        "auohstosh01.oracleoutsourcing.com",
        "autodeskvault2024.elink.elia.be",
        "autodiscover.*",
        "autodiscover.smflc.co.jp",
        "autodiscovery.geappliances.com",
        "beta.medicalogic.com",
        "bhge-mc.docksal",
        "bhge.bhge-mc.docksal",
        "bmsmetcalf.ercgroup.com",
        "bmsstateline.ercgroup.com",
        "bportugal.net",
        "brspbpsapp05.deloitte.com.br",
        "bsz.gironet.giro.hu",
        "caliber.deio.net",
        "calm-corella.ren.apps.gevernova.com",
        "catswebprod.edc.cingular.net",
        "chat.sc.ad.shinseifinancial.co.jp",
        "ciclaims.geercgroup.com",
        "cin-empcs-vendorapps.duke-energy.com",
        "cloudproxy.setpac.gevernova.com",
        "clt-citrix-vendorapps.duke-energy.com",
        "clt-empcs-vendorapps.duke-energy.com",
        "connect.dresserwayne.com",
        "corella.ren.apps.gevernova.com",
        "corp.riotinto.org",
        "cps.web.att.com",
        "csb2b.geaviationsystems.com",
        "csb2bt.geaviationsystems.com",
        "data.sc.ad.shinseifinancial.co.jp",
        "dbc-0343ced9-2875.cloud.databricks.com",
        "dbc-9eff6a74-df73.cloud.databricks.com",
        "dbc-dp-1261965901764080.cloud.databricks.com",
        "dbc-dp-1736447610121350.cloud.databricks.com",
        "dbc-dp-2228665913311758.cloud.databricks.com",
        "dbc-dp-3088546713863938.cloud.databricks.com",
        "dbc-dp-4625866504375480.cloud.databricks.com",
        "dbc-dp-5300162728839776.cloud.databricks.com",
        "dbc-dp-6600860889934619.cloud.databricks.com",
        "dbc-dp-8922641446284646.cloud.databricks.com",
        "deio.e-knowasp.com",
        "dev.com",
        "dev.jeff.geblogs.com",
        "dmdcwww01.fandango.com",
        "dosxx.acxiomhosting.com",
        "dslauncher.3ds.com",
        "dverp04.doosanvina.com.vn",
        "dverp18.doosanvina.com.vn",
        "dwb.stengg.us",
        "dweb01.fandango.com",
        "e-operations.web.att.com",
        "ebiznet.sbc.com",
        "edmdote.bakerhughes.com",
        "ehrms.adphc.com",
        "ejf.it.att.com",
        "emprunteur-gemb.sesame-cbp.fr",
        "emprunteur-recettegemb.sesame-cbp.fr",
        "emprunteur.sesame-cbp.fr",
        "enapp.quinnpumps.com",
        "eosvtstaic1.geeos.hu",
        "epp-dweb01.fandango.com",
        "epp-qweb01.fandango.com",
        "erc.gecapital.com",
        "erceaudit.com",
        "ercgrouphipaa.com",
        "eu-vault-corella.ren.apps.gevernova.com",
        "f1-corella.ren.apps.gevernova.com",
        "financecorp.biz",
        "flrnp.fdnet.com",
        "fnix.fandango.com",
        "formplm.eprnm.edf.fr",
        "ftp02.speedpay.com",
        "ge.hof.co.uk",
        "geam.blackrock.com",
        "gedrive.com",
        "geerc.com",
        "geercdashboard.com",
        "geerchealthcare.com",
        "geglobalunderwriting.com",
        "geolink.att.com",
        "gevernova-ai-dbr.cloud.databricks.com",
        "gevernova-ai-dev-dbr.cloud.databricks.com",
        "gevernova-ai-qa-dbr.cloud.databricks.com",
        "gevernova-ai-stg-dbr.cloud.databricks.com",
        "gevernova-cdl-dbr.cloud.databricks.com",
        "gevernova-cdl-dev-dbr.cloud.databricks.com",
        "gevernova-gas-power-dbr.cloud.databricks.com",
        "gevernova-gas-power-dev-dbr.cloud.databricks.com",
        "gevernova-hq-dbr.cloud.databricks.com",
        "gevernova-hq-dev-dbr.cloud.databricks.com",
        "gevernova-hq-fdl-naksha-ai-dbr.cloud.databricks.com",
        "gevernova-hq-fdl-qa-dbr.cloud.databricks.com",
        "gevernova-hq-fdl-vernil-dbr.cloud.databricks.com",
        "gevernova-innov-1.cloud.databricks.com",
        "gevernova-nrc-workspace.cloud.databricks.com",
        "gevernova-nuclear-dbr.cloud.databricks.com",
        "gevernova-nuclear-dev-dbr.cloud.databricks.com",
        "gevernova-vernova-ss.cloud.databricks.com",
        "gevernova-wind-dbr.cloud.databricks.com",
        "gevernova-wind-dev-dbr.cloud.databricks.com",
        "gevu.vingmed.no",
        "gla.geolink.att.com",
        "glhetreaties.geercgroup.com",
        "glheunderwriting.geercgroup.com",
        "glpwcndlc1scm01.dl.gcorp.ad",
        "got.niaepnn.ru",
        "hq.medicalogic.com",
        "idp-ccrt.ccc.cea.fr",
        "ilx.net",
        "industrialrisk.com",
        "inkolm*.tcs.com",
        "inside.fandango.com",
        "insidege.com",
        "intranet.use.ucdp.net",
        "iptv.zrh.swissre.com",
        "irctcprod.sbic.sbicard.com",
        "irctcuat.sbic.sbicard.com",
        "iscnervecenterdevadx.eastus.kusto.windows.net",
        "iscnervecenterprdadx.eastus.kusto.windows.net",
        "iwa-sso.bakerhughes.com",
        "keycloak-prod.prd-0000062.paeuw1.bakerhughes.com",
        "killians.acxiomhosting.com",
        "kspz0145.kcdc.att.com",
        "library.sc.ad.shinseifinancial.co.jp",
        "live.ngrid-clm.com",
        "local",
        "local.connectme.us",
        "localhost.emudhra.com",
        "localhost.localdomain",
        "login.microsoftonline.com",
        "lufkin.com",
        "maewest.atlprom.att.com",
        "mail.geappliances.com",
        "mail.smflc.co.jp",
        "medprong.geercgroup.com",
        "mmreports.amer.umusic.net",
        "mwtig.mi.sbc.com",
        "my.firewall",
        "myid.bakerhughes.com",
        "myonlinestore*.gecitsolutions.com",
        "myreinsurance.com",
        "naksha-poc-8922641446284646.aws.databricksapps.com",
        "nbo-online.no",
        "ncpc.bakerhughes.com",
        "ncr-ogi.azure.bakerhughes.com",
        "net-vision.sita.net",
        "nja76.speedpay.com",
        "nmw-app-3psaerwhnbrmy.azurewebsites.net",
        "noosd001.com",
        "nsdnet.web.att.com",
        "oa.e-i.com",
        "pdm.ideal.com",
        "pdm.idel.com",
        "pfd.cpmarket.com",
        "plf-empcs-vendorapps.duke-energy.com",
        "plm.corporate.lufkin.com",
        "plm.eprnm.edf.fr",
        "plmxazrtcrds-0.xignux.com",
        "pmijpwebsblp01.app.pmi",
        "portal.hilan.co.il",
        "portal.sibs.pt",
        "pplsrch.supportcentral.synchronyfinancial.com",
        "prod-edmdote.bakerhughes.com",
        "production.wayne.com",
        "qa-corella.ren.apps.gevernova.com",
        "qa-eu-vault-corella.ren.apps.gevernova.com",
        "qa-f1-corella.ren.apps.gevernova.com",
        "qa-f4-corella.ren.apps.gevernova.com",
        "qmdcwww01.fandango.com",
        "quadrant.statestr.com",
        "quinnpumps.com",
        "qweb01.fandango.com",
        "ral-citrix-vendorapps.duke-energy.com",
        "rc.gecapital.com",
        "registers.nzta.govt.nz",
        "remote.geappliances.com",
        "remoteoffice.ams.com.au",
        "repaironeportal-prod.prd-0000109.paeuw1.bakerhughes.com",
        "sapotaprd1.mras.stengg.us",
        "sapotcprd1.mras.stengg.us",
        "sapps1.stengg.us",
        "sc.ad.shinseifinancial.co.jp",
        "sc.synchronyfinancial.com",
        "sccm.ibcm.genpact.com",
        "scg.hostedeet.com",
        "search.sc.ad.shinseifinancial.co.jp",
        "securesignir.com",
        "servicecatalog.azure.bakerhughes.com",
        "servicecatalog.ent.bhicorp.com",
        "servicedesk.itt.att.com",
        "servicedesk.tipeurope.com",
        "sharepoint.industrea.co",
        "sharepoint.use.ucdp.net",
        "sip.reuters.net",
        "softwarecert.usc.swissre.com",
        "solvwebchat.bakerhughes.com",
        "spdm.avioaero.com",
        "spdm.aviogroup.com",
        "spreports.accentonline.com",
        "srvspeq.dresserconsolidated.com",
        "stage.jeff.geblogs.com",
        "statebanktimes.in",
        "storage-eb4-private.cegedim.cloud",
        "stssky.smflc.co.jp",
        "supportcentral.gesupply.com",
        "sydtefwb1commge.gecommercial.com.au",
        "tabdb.sbc.com",
        "tcs01hw325310-vm*.tcs.com",
        "test-gefasso.ltcdigitaloffice.com",
        "test.geonline.lv",
        "timecard.wayne.com",
        "tosh1.oraclebol.com",
        "tosh1ftp.oraclebol.com",
        "trapeze.tcs.com",
        "tsapps.gerbc.rbcmtg.com",
        "tss.sbc.com",
        "ttbucolo01.fandango.com",
        "tv-empcs-vendorapps.duke-energy.com",
        "uai3067053-askalta-chatbot-dev-com2-app-wn.azurewebsites.net",
        "uapit*.sabic-ip.com",
        "ukgcd001.com",
        "uoccr.use.ucdp.net",
        "uoear.use.ucdp.net",
        "uolrp.use.ucdp.net",
        "uowf.use.ucdp.net",
        "us-vault-corella.ren.apps.gevernova.com",
        "usahd001.com",
        "usanetworks.com",
        "usprd001.com",
        "vendor.geolink.att.com",
        "vertigo1.necn.com",
        "vetco.com",
        "vetcogray.com",
        "vetcogray.no",
        "vips.web.att.com",
        "vipsf.tipeurope.com",
        "visu-ccrt.ccc.cea.fr",
        "vitalconnect.myappsge.com",
        "vpn.geappliances.com",
        "waveqms.wavebiotech.com",
        "wc-master1.corporate.lufkin.com",
        "wc-slave1.corporate.lufkin.com",
        "wc-slave2.corporate.lufkin.com",
        "web.pensketruckleasing.com",
        "webconf.zrh.swissre.com",
        "windchill-repl.corporate.lufkin.com",
        "woodduck.web.att.com",
        "workplace.csc.com",
        "wow.corp.compucom.com",
        "wpcii.insurity.com",
        "wss.singlewindow.cn",
        "www-ccrt.ccc.cea.fr",
        "www.e-access.att.com",
        "www.e-access.bls.com",
        "www.e-access.cingular.net",
        "www.gemicroapp.com",
        "www.gemicroappdev.com",
        "www.gemicroapppilot.com",
        "www.geolink.att.com",
        "www.ibank.insurity.com",
        "www.iisonline.statestreet.com",
        "www.infodealer.com",
        "xenapp.quinnpumps.com",
        "xww.ge.world.xerox.com"
    ],
    //EndDoNotSendToProxy

    // AD Proxy domains
    SendToADProxy: [ "autodiscover.gecompany.mail.onmicrosoft.com" ],
    //EndSendToADProxy

    // EXOL domains
    SendToExolER: [],
    //EndSendEXOLProxy

    // Directly sent domains
    SendDirect: [
        ".myhost.gehealthcare.com",
        ".private.o365.ge.com",
        ".rationalalmus.geaviation.com",
        "login.windows.net",
        "myhost.gehealthcare.com",
        "pod51090.outlook.com",
        "pod51098.outlook.com",
        "pod51107.outlook.com"
    ]
    //EndSendDirect

};
//EndHOSTS

// Function to check if Host is GE Internal IP, called by Used in function FindProxyForURL
// Warning - Use this function only on IP addresses to avoid DNS queries
function isInternalIP(host) {
    "use strict";
    return (
        isInNet(host, "10.0.0.0", "255.0.0.0") ||
        isInNet(host, "119.43.0.0", "255.255.0.0") ||
        isInNet(host, "124.4.0.0", "255.255.0.0") ||
        isInNet(host, "127.0.0.0", "255.0.0.0") ||
        isInNet(host, "129.201.0.0", "255.255.0.0") ||
        isInNet(host, "129.202.0.0", "255.255.0.0") ||
        isInNet(host, "147.90.0.0", "255.255.0.0") ||
        isInNet(host, "151.186.0.0", "255.255.0.0") ||
        isInNet(host, "151.95.0.0", "255.255.0.0") ||
        isInNet(host, "155.90.0.0", "255.255.0.0") ||
        isInNet(host, "167.16.0.0", "255.255.0.0") ||
        isInNet(host, "170.14.0.0", "255.255.0.0") ||
        isInNet(host, "170.186.0.0", "255.255.0.0") ||
        isInNet(host, "172.16.0.0", "255.240.0.0") ||
        isInNet(host, "182.94.0.0", "255.255.0.0") ||
        isInNet(host, "182.95.0.0", "255.255.0.0") ||
        isInNet(host, "192.168.0.0", "255.255.0.0") ||
        isInNet(host, "192.35.38.0", "255.255.254.0") ||
        isInNet(host, "192.35.40.0", "255.255.254.0") ||
        isInNet(host, "192.88.213.0", "255.255.255.0") ||
        isInNet(host, "198.178.252.0", "255.255.255.0") ||
        isInNet(host, "199.181.101.0", "255.255.255.0") ||
        isInNet(host, "199.181.102.0", "255.255.255.0") ||
        isInNet(host, "20.131.2.0", "255.255.255.0") ||
        isInNet(host, "203.12.79.0", "255.255.255.0") ||
        isInNet(host, "204.124.0.0", "255.255.0.0") ||
        isInNet(host, "206.201.0.0", "255.255.0.0") ||
        isInNet(host, "3.0.0.0", "255.0.0.0") ||
        isInNet(host, "58.2.0.0", "255.255.0.0") ||
        isInNet(host, "58.2.0.0", "255.255.255.0") ||
        isInNet(host, "58.2.139.0", "255.255.255.0") ||
        isInNet(host, "58.2.47.0", "255.255.255.0") ||
        isInNet(host, "64.101.239.0", "255.255.255.0") ||
        (host == "12.47.84.17") ||
        (host == "131.99.76.121") ||
        (host == "138.66.30.20") ||
        (host == "140.85.171.9") ||
        (host == "140.85.253.19") ||
        (host == "140.85.253.250") ||
        (host == "140.85.253.251") ||
        (host == "140.85.253.252") ||
        (host == "140.85.253.254") ||
        (host == "146.192.196.132") ||
        (host == "146.192.196.151") ||
        (host == "155.195.0.1") ||
        (host == "168.183.239.111") ||
        (host == "168.183.239.112") ||
        (host == "170.70.91.100") ||
        (host == "170.70.91.23") ||
        (host == "192.131.230.144") ||
        (host == "193.15.242.105") ||
        (host == "193.15.242.106") ||
        (host == "193.161.30.184") ||
        (host == "193.182.21.40") ||
        (host == "194.30.165.101") ||
        (host == "194.30.165.104") ||
        (host == "198.151.229.10") ||
        (host == "202.144.30.124") ||
        (host == "202.2.59.12") ||
        (host == "203.0.138.17") ||
        (host == "203.0.138.18") ||
        (host == "203.12.79.76") ||
        (host == "204.90.182.186") ||
        (host == "207.248.70.196") ||
        (host == "207.248.70.197") ||
        (host == "207.248.70.198") ||
        (host == "207.248.70.252") ||
        (host == "207.248.70.44") ||
        (host == "207.248.70.49") ||
        (host == "207.248.70.54") ||
        (host == "208.253.54.125") ||
        (host == "212.239.27.156") ||
        (host == "212.70.166.3") ||
        (host == "212.70.166.4") ||
        (host == "216.46.96.243") ||
        (host == "4.23.177.166") ||
        (host == "58.2.71.98") ||
        (host == "62.184.124.1") ||
        (host == "66.241.52.13") ||
        (host == "67.56.128.1") ||
        (host == "67.56.184.1")
    );
}
//Endfunction isInternalIP

// Function to search  entries in HOSTS Array
function findHostInArray(host, aElements) {
    "use strict";
    var i = aElements.length;
    var h = host.toLowerCase();
    while (i--) {
        // If Host is in array the return true
        if (h === aElements[i]) {
            return true;
        }
        // check if Array entry starts with "."
        if (aElements[i].charAt(0) == '.') {
            // Matches only the Domain part from host (FQDN)  Equivalent to dnsDomainIs function
            if (h.substring(h.length - aElements[i].length, h.length) == aElements[i]) {
                return true;
            } else {
                if (aElements[i].substring(1, aElements[i].length) == h) {
                    return true;
                }
            }
        } else {
            // To match host against wildcard entries in array
            if (aElements[i].indexOf("*") >= 0) {
                if (shExpMatch(h, aElements[i])) {
                    return true;
                }
            }
        }
    }
    return false;
}
//EndFunction findHostInArray

// Main Function
function FindProxyForURL(url, host) {
    "use strict";
    // If there are more entries which goes to any other special proxies, then entries goes here
    if (findHostInArray(host, HOSTS.SendToOtherProxy2))  return Other_Proxy2;

    // O365 authentication
    if (findHostInArray(host, HOSTS.SendToADProxy))  return AD_Proxy;

    // Domains that need to go Internal 
    if (findHostInArray(host, HOSTS.SendDirect)) return "DIRECT";

    // Microsoft ExpressRoute for EXOL traffic
    if (findHostInArray(host, HOSTS.SendToExolER))  return EXOL_ExpressRoute;

    // GDC Parent Proxy, Regional Proxy and Other Special Proxies
    if (findHostInArray(host, HOSTS.SendToOtherProxy))  return Other_Proxy;

    if (ipv4addr.test(host)) {
        if (isInternalIP(host)) {
            return "DIRECT";
        }
    }

    if (isPlainHostName(host)) {
        return "DIRECT";
    }

    if (findHostInArray(host, HOSTS.SendToZen)) {
        return pZen;
    }

    //  Function used to route traffic towards proxy from GE Internal Domains Ex- www.ge.com
    //  A DNS entry for each such host is required in Internal domain with IP as 223.255.255.255
    if (findHostInArray(host, HOSTS.SplitDNSDomains)) {
        if (dnsResolve(host) === "223.255.255.255") {
            return Main_Proxy;
        }
    }

    if (findHostInArray(host, HOSTS.SendToProxy)) {
        return Main_Proxy;
    }

    if (findHostInArray(host, HOSTS.DoNotSendToProxy)) {
        return "DIRECT";
    }

    return Main_Proxy;
}
//Endfunction FindProxyForURL